### ISSUE TITLE
Assigned Loot Issues - Clicking outside loot dialog box doesn't assign loot and assigned loot is immutable to a character

### ISSUE THREAD

**Issue by Bnibling** [Lurkars/gloomhavensecretariat#156]
With "Always show Loot Apply Dialog" checked, if you click outside the dialog box, it doesn't assign the loot to a character. There is no class icon on the loot card and I've confirmed that loot is not added to any character sheet with Success on the scenario.

Issue two is editing assigned loot cards. With "Edit" checked, if you put a previously assigned loot card back into the deck and redraw it, it maintains it previous assignment along with the new assignment (effectively doubling the loot card, even if assigned to same character as before). 

So, if you misclicked outside the dialog box 2 loot cards ago, but assigned the most recent loot card:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/48171929/224068475-7cd93af7-2356-465b-ab3a-82e870534b28.png">

And you edit, putting both cards back in to assign the missed loot card: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/48171929/224068717-314ca945-8da8-4d97-b15a-f29a1f3450be.png">

The loot card that was previously assigned is duplicated to the character is was assigned to:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/48171929/224069274-a4a94d80-bd2a-4d94-94c5-e06d0165bb96.png">

So, short of the "Undo" button (which can be tedious if not caught immediately), there is no way to retroactively re-assign a loot card (which would be a nice feature).

**Comment by Bnibling** [comment]
Another issue: Loot assignment isn't assigned to the loot card and appears to be assigned to the index of the draw loot cards. 

Same scenario above, assigned the most recent loot card but not the one before that:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/48171929/224076898-0184e1a6-dc63-4859-a4ba-d9114a3fb476.png">

Edit to add the unassigned loot card back causes the assigned card to lose assignment:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/48171929/224077431-052ce5ba-a6d5-4844-9600-8eb9d09789ca.png">

Redraw and assign duplicates the loot card and leaves previously assigned card unassigned:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/48171929/224077649-eafd1393-77fc-4869-9a83-1a4e3821b66b.png">
 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/48171929/224077789-cd209dd0-9728-47fa-9bfe-97476f6cc2b6.png">

**Comment by Lurkars** [comment]
Thanks. That are some nice findings. I think I will just implement a mechanic to (re)assign loot in the edit dialog to a character. That will be than also a fix to your first point.

**Comment by Lurkars** [comment]
Sorry no time for screenshots, I hope everything is fixed in [v0.49.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.6).

If apply loot is enabled but not assigned, a red alert symbol. In dialog, you can then assign loot card. If edit enabled, you can also click on character icon and reassign. Sorting should also work. Please verify and give feedback. Thanks

**Comment by Bnibling** [comment]
Tested all prior cases and Red alert symbol works where loot is unassigned and edit enabled works for reassigning via class icon.

However, there is still an issue with reordering loot cards. This is likely an edge case, but if you edit and shuffle a loot card back into the deck (whether it is assigned or not):
<img width="560" alt="image" src="https://user-images.githubusercontent.com/48171929/224136651-2278828b-35bd-406f-9c00-01fc4d5d01a5.png">

The loot card before it gets unassigned:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/48171929/224136761-3d6c3103-eaa9-43a0-84be-eb758691dee0.png">

If you try to reassign this card, it keeps a red alert symbol, and the loot card you shuffled back in gets duped onto the character:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/48171929/224137122-87850f12-ec25-4ede-8a67-64bc69f92ee7.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/48171929/224137444-ff7b9c92-b914-4fa0-ba22-c3b8b8a6bfa9.png">

If you close the window prior to reassigning, it works as intended however. Again this is an edge case, but something I found.

**Comment by Lurkars** [comment]
Ough, that took me a while. So hopefully it now works in  [v0.49.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.7). Can you please test again? Thank you!

**Comment by Lurkars** [comment]
Ough, hopefully now really fixed in [v0.49.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.7). Can you please verify again? Thanks.

**Comment by Bnibling** [comment]
Passed all tests on my end! Great job! :)

**Comment by Lurkars** [comment]
I hope this isn't irritating now too much, but I moved the char icon to the left in [v0.49.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.8) because then it is also visible on second card of loot deck. Hope that's okay.
