### ISSUE TITLE
Summons conditions remove when clicking summoners portrait.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#602]
### Describe the bug

Not sure if this is a bug but when a summon has muddle or similar and you click on the summoners turn to activate them, the conditions remove. This makes it hard to perform your summons turns because then you can't remember if they had muddle or immobilize etc.

### Game Enviroment

Seems to be the same with or without Active Summons on. In fact, I don't think the Active Summons setting works....

### To Reproduce

1. Begin round with summon having muddle or similar. 
2. Start summoners turn.
3. Summon loses muddle.

### Expected behavior

The summon's conditions should stay until the summoners turn is over. Things like wound or regenerate should still go off though on activating the summoners turn. Maybe this isn't possible and it's either or?

### Gloomhaven Secretariat Version

v.0.99.18

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
I think this is related to active summons and a failed fix for #598.
In [v0.99.19](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.19) it should be fixed now. Happy if you can check and close issue if solved.

**Comment by Kafei56** [comment]
Looks like it's fixed when active summons is disabled, but enabling active summons it's still the same and the summons aren't activating.

**Comment by Lurkars** [comment]
Cannot reproduce on my side. Can you describe in more detail what your steps are?
